name: OneInTheChamber
version: 0.1
description: One In The Chamber
author: Mountier, LunarNova, Flenk
main: world.oitc.Main

commands:
   oitc:
      usage: /oitc <subCmd>
      description: OITC Administration 
      permission: oitc.admin
permissions:
   oitc.admin:
      default: OP
      description: OITC Administration